project:
  type: website
  output-dir: docs
  render:
    - "!*.md"
    - "*.qmd"
website:
  title: "UCLA Biostatistics Student Association"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - board.qmd
      - events.qmd
      - newsletter/newsletter.qmd
    right:
      - href: https://ph.ucla.edu/departments/biostatistics
        text: UCLA Biostatistics
    

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



