project:
  type: website
  output-dir: docs
  #pre-render: directory/make_profiles.R # comment out if you don't need to create student profiles each time
  render:
    - "!*.md"
    - "!*test*.qmd"
    - "*.qmd"
website:
  title: "UCLA Biostatistics Student Association"
  favicon: images/icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/about.qmd
        text: About
      - href: directory/directory.qmd
        text: Student Directory
      - href: events/events.qmd
        text: Events
    right:
      - href: https://ph.ucla.edu/departments/biostatistics
        text: UCLA Biostatistics
        target: _blank
  page-footer:
    right:
      - icon: github
        href: https://github.com/UCLA-BSA/UCLA-BSA.github.io
        target: _blank
    

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 300px
    include-in-header: directory/scramble_email.html
    link-external-newwindow: true
    link-external-filter: '.*'

    

    