# build_directory_index.R
# Scans docs/directory/profiles/ and generates about/directory-index.js
# so the about page can resolve a board member's name -> profile path automatically.
#
# Run from the repo root:
#   Rscript directory/build_directory_index.R
#
# Re-run whenever the student directory changes (after make_profiles.R + quarto render).

library(jsonlite)

profiles_dir <- "docs/directory/profiles"
out_file     <- "about/directory-index.js"
prog_types   <- c("phd", "ms", "mdsh")

index <- list()

for (prog_type in prog_types) {
  folder <- file.path(profiles_dir, prog_type)
  if (!dir.exists(folder)) next

  html_files <- list.files(folder, pattern = "\\.html$", full.names = FALSE)

  for (fname in html_files) {
    stem <- sub("\\.html$", "", fname)  # e.g. "darren-lin-phd-50"

    # Must match: {name-slug}-{phd|ms|mdsh}-{number}
    if (!grepl("^.+-(phd|ms|mdsh)-\\d+$", stem)) next

    # Strip the -type-number suffix to get the name slug
    name_slug <- sub("-(phd|ms|mdsh)-\\d+$", "", stem)  # e.g. "darren-lin"

    # Convert slug to Title Case ("darren-lin" -> "Darren Lin")
    full_name <- paste(
      sapply(strsplit(name_slug, "-")[[1]], function(w) {
        paste0(toupper(substr(w, 1, 1)), substr(w, 2, nchar(w)))
      }),
      collapse = " "
    )

    index[[full_name]] <- paste0(prog_type, "/", stem)
  }
}

# Sort alphabetically by name
index <- index[order(names(index))]

# Serialise to JSON (handles escaping automatically)
json_body <- toJSON(index, auto_unbox = TRUE, pretty = TRUE)

js <- paste0(
  "// AUTO-GENERATED by directory/build_directory_index.R — do not edit by hand\n",
  "// Re-run the script whenever the student directory is updated.\n",
  "window.BSA_DIRECTORY_INDEX = ", json_body, ";\n"
)

writeLines(js, out_file)

