#!/usr/bin/env python3
"""
Scans docs/directory/profiles/ and generates about/directory-index.js
so the about page can resolve a board member's name → profilePath automatically.

Run from the repo root:
    python3 scripts/build-directory-index.py

Re-run whenever the student directory changes.
"""

import os, re, json

PROFILES_DIR = "docs/directory/profiles"
OUT_FILE     = "about/directory-index.js"
TYPES        = ["phd", "ms", "mdsh"]

# Regex: strips the -type-id suffix from the filename stem
# e.g. "timothy-shen-phd-6" → name_slug="timothy-shen", type="phd"
SUFFIX_RE = re.compile(r'^(.+?)-(phd|ms|mdsh)-\d+$')

index = {}   # "Full Name" -> "type/stem-type-id"

for prog_type in TYPES:
    folder = os.path.join(PROFILES_DIR, prog_type)
    if not os.path.isdir(folder):
        continue
    for fname in os.listdir(folder):
        if not fname.endswith(".html"):
            continue
        stem = fname[:-5]          # strip .html
        m = SUFFIX_RE.match(stem)
        if not m:
            continue
        name_slug = m.group(1)     # e.g. "timothy-shen"
        # Convert slug → Title Case ("timothy-shen" → "Timothy Shen")
        full_name = " ".join(part.capitalize() for part in name_slug.split("-"))
        profile_path = f"{prog_type}/{stem}"
        index[full_name] = profile_path

# Write JS file
lines = ["// AUTO-GENERATED by scripts/build-directory-index.py — do not edit by hand",
         "// Re-run the script whenever the student directory is updated.",
         "window.BSA_DIRECTORY_INDEX = " + json.dumps(index, indent=2, ensure_ascii=False) + ";"]

with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {len(index)} entries → {OUT_FILE}")
for name, path in sorted(index.items()):
    print(f"  {name!r:40s} → {path}")
