name: Update and Build Biostatistics Student Directory

on:
  schedule:
    # Runs at 09:00 every Monday
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.DIRECTORY_BOT_APP_ID }}
          private_key: ${{ secrets.DIRECTORY_BOT_APP_PRIVATE_KEY }}
          
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }} 
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::googledrive
            any::googlesheets4
            any::glue
            any::dotenv
            any::here
            any::writexl
            any::readxl
          cache-version: 1

      - name: Run R script to generate profiles
        env:
          GDRIVE_JSON: ${{ secrets.GDRIVE_JSON }}
          STUDENT_DIRECTORY_URL: ${{ secrets.STUDENT_DIRECTORY_URL }}
        run: Rscript directory/workflow_make_profiles.R

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Build Quarto site
        run: quarto render

      - name: Commit and push .qmd profiles
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add directory/profiles/
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update student directory profiles"
            git pull --rebase origin main
            git push origin main
          fi
        env:
          # This ensures the 'git push' command uses the App token
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Publish to GitHub Pages (Action)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}